;#########  SPYBOT INSTALL

WinWaitActive("Select Setup Language", "Select the language to use")
				ControlClick("Select Setup Language", "Select the language to use", "TNewButton1")
				WinWaitActive("Setup - Spybot - Search & Destroy", "This will install Spybot")
				ControlClick("Setup - Spybot - Search & Destroy", "This will install Spybot", "TNewButton1")
				WinWaitActive("Setup - Spybot - Search & Destroy", "Please read the following License")
				ControlClick("Setup - Spybot - Search & Destroy", "Please read the following License", "TNewRadioButton1")
				ControlClick("Setup - Spybot - Search & Destroy", "Please read the following License", "TNewButton2")
				WinWaitActive("Setup - Spybot - Search & Destroy", "Setup will install Spybot")
				ControlClick("Setup - Spybot - Search & Destroy", "Setup will install Spybot", "TNewButton3")
				Sleep(2000)
				If WinActive("Folder Exists", "") Then
					ControlClick("Folder Exists", "", "Button1")
				EndIf
				WinWaitActive("Setup - Spybot - Search & Destroy", "Select the components you want to install")
				ControlClick("Setup - Spybot - Search & Destroy", "Select the components you want to install", "TNewButton3")
				WinWaitActive("Setup - Spybot - Search & Destroy", "Setup will create the program's shortcuts")
				ControlClick("Setup - Spybot - Search & Destroy", "Setup will create the program's shortcuts", "TNewButton4")
				WinWaitActive("Setup - Spybot - Search & Destroy", "Select the additional tasks")
				Send("{DOWN}{DOWN}{DOWN}{SPACE}{ENTER}")
				WinWaitActive("Setup - Spybot - Search & Destroy", "Click Install to continue")
				ControlClick("Setup - Spybot - Search & Destroy", "Click Install to continue", "TNewButton4")
				Sleep(3000)
				If WinActive("File Download", "Error") Then
					Send("{ENTER}")
				EndIf
				If WinActive("Setup - Spybot - Search & Destroy", "Click Install to continue") Then
					Send("!i")
				EndIf
				WinWaitActive("Setup - Spybot - Search & Destroy", "Completing the Spybot")
				ControlClick("Setup - Spybot - Search & Destroy", "Completing the Spybot", "TNewButton4")
				WinWait("Legal stuff", "")
				ControlClick("Legal stuff", "", "TCheckBox1")
				ControlClick("Legal stuff", "", "TBitBtn1")
				WinWait("Spybot-S&D Wizard")
				WinActivate("Spybot-S&D Wizard")
				Send("!e")
				Send("!e")
				Send("!e")
				Send("!e")
				ControlClick("Spybot-S&D Wizard", "", "TButton2")
				WinWaitActive("Spybot - Search & Destroy", "")
				Send("!u")
				WinWaitActive("Spybot-S&D Updater", "")
				Sleep(2000)
				Send("!c")
				WinWaitActive("Spybot-S&D Updater", "")
				Sleep(2000)
				Send("!d")
				WinWait("Legal stuff", "")
				ControlClick("Legal stuff", "", "TCheckBox1")
				ControlClick("Legal stuff", "", "TBitBtn1")
				WinWaitActive("Spybot - Search & Destroy", "")
				Send("!i")
				Sleep(15000)
				Send("!i")
				Sleep(5000)
				Send("{ALT}")
				Send("{DOWN}")
				Send("{ENTER}")