;###############  SUPER-ANTI-SPYWARE INSTALL

WinWaitActive("SUPERAntiSpyware Free Edition Setup", "It is strongly recommended", 15)
ControlClick("SUPERAntiSpyware Free Edition Setup", "It is strongly recommended", "Button8")
WinWaitActive("SUPERAntiSpyware Free Edition Setup", "SUPERAntiSpyware License Terms", 15)
ControlClick("SUPERAntiSpyware Free Edition Setup", "SUPERAntiSpyware License Terms", "Button8")
WinWaitActive("SUPERAntiSpyware Free Edition Setup", "The settings for this application", 15)
ControlClick("SUPERAntiSpyware Free Edition Setup", "The settings for this application", "Button8")
WinWaitActive("SUPERAntiSpyware Free Edition Setup", "Browse", 15)
ControlClick("SUPERAntiSpyware Free Edition Setup", "Browse", "Button8")
WinWaitActive("SUPERAntiSpyware Free Edition Setup", "The following options will be used", 15)
ControlClick("SUPERAntiSpyware Free Edition Setup", "The following options will be used", "Button2")
ControlClick("SUPERAntiSpyware Free Edition Setup", "The following options will be used", "Button3")
ControlClick("SUPERAntiSpyware Free Edition Setup", "The following options will be used", "Button8")
WinWaitActive("SUPERAntiSpyware Free Edition Setup", "Click the Finished button", 15)
ControlClick("SUPERAntiSpyware Free Edition Setup", "Click the Finished button", "Button9")
WinWaitActive("SUPERAntiSpyware Free Edition", "Scans your computer for Spyware", 120)
ControlClick("SUPERAntiSpyware Free Edition", "Scans your computer for Spyware", "Button3")
ControlClick("SUPERAntiSpyware Free Edition", "Scans your computer for Spyware", "Button1")
WinWaitActive("SUPERAntiSpyware Free Edition", "Scans all running items", 15)
ControlClick("SUPERAntiSpyware Free Edition", "Scans all running items", "Button23")
ControlClick("SUPERAntiSpyware Free Edition", "Scans all running items", "Button21")